### ISSUE TITLE
Start Page

### ISSUE THREAD

**Issue by Bennaiii** [kevpeng/burger-skeleton#10]
- [x] **Start Page**
  - [x] Page Text ("Do you want to eat in or Take away?")
  - [x] Eat-in/Takeaway Buttons

**Comment by kevpeng** [comment]
Kevin do this

**Comment by kevpeng** [comment]
need to reformat and link the pages, but the content is there

**Comment by kevpeng** [comment]
Pretty sure it's done at this point
