### ISSUE TITLE
Time out

### ISSUE THREAD

**Issue by Bennaiii** [kevpeng/burger-skeleton#11]
**Time out**
  - [x] Time out after 40s
  - [x] remove current Order when Time out
  - [x] alter pop up and viewing counter + cancel button

**Comment by kevpeng** [comment]
Figured out how to do time out. Need the ordering part to work before continuing

**Comment by Bennaiii** [comment]
you can add objects to the selection now using the add buttons :)
if you need something in the order object, simply click "pay" and the selection object will be moved into the order object

**Comment by Bennaiii** [comment]
and please specify how/where the timeout is working, because in BurgerCreation & SelectionOverview nothing happens after 1min o.o

**Comment by kevpeng** [comment]
check group chat for details

**Comment by kevpeng** [comment]
done
