### ISSUE TITLE
Cart Pop Up

### ISSUE THREAD

**Issue by Bennaiii** [kevpeng/burger-skeleton#5]
- [x] Title ("Your choices")
  - [x] List of Items
      - [x] switchting language of items
  - [x] "Remove" Buttons for Items (Optional: Edit Amount of each Item)
  - [x] Pay Button
  - [x] Scrollable (for longer orders, otherwise you can't pay)
  - ~~Blur Background~~
  - ~~Click anywhere outside the Pop Up to close it (remove the "focus")~~

**Comment by Lenny04** [comment]
This feature: Click anywhere outside the Pop Up to close it (remove the "focus"), I haven't implemented it, because I think it is enough that the user can click on the cart icon to open and close the cart

**Comment by Lenny04** [comment]
I don't think the feature: Blur Background, is needed either

**Comment by Lenny04** [comment]
Can't this feature: switchting language of items, be implemented by changing the properties for each item obj, so instead of only having one "name", each will have both the english and swedish name, so we have access to both when wanting to show the name?
