### ISSUE TITLE
Premade Food Selection Pages

### ISSUE THREAD

**Issue by Bennaiii** [kevpeng/burger-skeleton#6]
(Menus, Burgers, Fries, Salad, Ice Cream, Drinks)
  - [x] Filter (gluten-free, lactose-free, vegetarian, vegan)
  - [x] "+/-" Buttons to Increase/Decrease Amount of Burgers
  - [x] Scroll bar
  - [x] Back/Add to Order Buttons (if something is selected)
  - [x] make the buttons centered

**Comment by Hvts3rk** [comment]
Giorgio's here
