### ISSUE TITLE
Ingridient Selection Pages

### ISSUE THREAD

**Issue by Bennaiii** [kevpeng/burger-skeleton#7]
(Bread, Patty, Toppings, Sauce)
  - [x] Filter (gluten-free, lactose-free, vegan)
  - [x] Line between Filter and Ingredients
  - [x] Ingridient Buttons 
  - [x] Multiple selection only for Toppings!
  - [x] Scroll bar
  - [x] Back/Add to Burger Buttons (if something is selected)

**Comment by juvabel** [comment]
julia
