### ISSUE TITLE
Burger Creation Page

### ISSUE THREAD

**Issue by Bennaiii** [kevpeng/burger-skeleton#8]
- [x] Page Title ("Burger Creation")
  - [x] Burger Picture
  - [x] Buttons for Bread, Patty, Toppings, Sauce
  - [x] Back/Add to Order Buttons  (if all mandatory burger items are selected)
  - [x] make the elements centered (also for smartphone view)

**Comment by juvabel** [comment]
julia

**Comment by Bennaiii** [comment]
- [ ] make the elements centered (also for smartphone view)
