### ISSUE TITLE
Selection Overview Page

### ISSUE THREAD

**Issue by Bennaiii** [kevpeng/burger-skeleton#9]
- [x] "Create own Burger" Button
  - [x] Line between Creation and Premade Food
  - [x] Buttons for Menus, Burgers, Fries, Salad, Ice Cream, Drinks
  - [x] Back Button
  - [x] Order&Pay Button
  - [x] Show Cart/any selection summary before continuing to payment

**Comment by Lenny04** [comment]
Linoj is working on this

**Comment by kevpeng** [comment]
- [x] Text for buttons should decrease dynamically if the screen size decreases to point where text is larger than button
